<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <RootNamespace>WOpenUsage.Platform.Windows</RootNamespace>
    <AssemblyName>WOpenUsage.Platform.Windows</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WOpenUsage.Core\WOpenUsage.Core.csproj" />
  </ItemGroup>

</Project>
