#!/usr/bin/env python3
"""Maintain deterministic documentation-source hashes, not a product signature."""
from __future__ import annotations
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXCLUDED = {
    'manifest.json',
    'validation/integration-validation.json',
    'validation/pack-validation.json',
    'validation/reader-validation.json',
}

def source_files() -> list[tuple[str, Path]]:
    collected: list[tuple[str, Path]] = []
    for p in ROOT.rglob('*'):
        if not p.is_file() or '__pycache__' in p.parts or '.venv-docs' in p.parts or '.git' in p.parts:
            continue
        relative = p.relative_to(ROOT).as_posix()
        if relative in EXCLUDED:
            continue
        collected.append((relative, p))
    collected.sort(key=lambda item: item[0])
    return collected


def build() -> str:
    registry = json.loads((ROOT / 'tools/reader-documents.json').read_text(encoding='utf-8'))
    files = []
    for relative, p in source_files():
        data = p.read_bytes()
        files.append({'path': relative, 'bytes': len(data), 'sha256': hashlib.sha256(data).hexdigest()})
    value = {
        'title': 'TokenUsage Reports Workbench — repository integration',
        'document_version': '2.1',
        'baseline_commit': 'df50c367b083e5624bf09213eddc7013d8299aa4',
        'status': 'local_complete_pr62_partial_pending_authorization',
        'stats': {
            'current_markdown_documents': sum(x['id'] != 'rfc-original' for x in registry),
            'archived_rfc_documents': 1,
            'phase_documents': 5,
            'phase_requirements': 36,
            'cross_cutting_requirements': 12,
            'additional_integration_requirements': 12,
            'implementation_tasks': 27,
            'planned_phase_test_cases': 56,
            'additional_planned_integration_cases': 12,
            'additional_planned_native_sqlite_cases': 6,
            'metric_definitions': 20,
            'draft_schemas': 3,
            'original_archives_preserved': 2,
        },
        'excluded_from_hashes': sorted(EXCLUDED),
        'exclusion_reason': 'This manifest cannot hash itself; live validation reports are regenerated by their checks. Historical reports remain hashed.',
        'integrity_notice': 'SHA-256 detects changes relative to this manifest; it is not a signature, authenticity proof, malware scan, or product test result.',
        'files': files,
    }
    return json.dumps(value, ensure_ascii=False, indent=2)+'\n'


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Check hashes without updating the manifest')
    args = parser.parse_args()
    content = build()
    target = ROOT / 'manifest.json'
    if args.check:
        if not target.exists() or target.read_text(encoding='utf-8') != content:
            print('Manifest differs from source files. Review changes before regenerating.')
            return 1
        print('Source manifest matches; no files written.')
    else:
        with target.open('w', encoding='utf-8', newline='\n') as stream:
            stream.write(content)
        print('Updated documentation source manifest.')
    return 0

if __name__ == '__main__':
    raise SystemExit(main())
